---
pushgateway_port: 127.0.0.1:9091
pushgateway_description: Pushgateway
pushgateway_volume_name: "{{ pushgateway_hostname }}"
pushgateway_data_dir: /usr/share/{{ pushgateway_hostname }}
pushgateway_etc_hosts: {}
pushgateway_nginx_data_dir: "{{ nginx_data_dir }}/proxies"
pushgateway_requires_package: python3-passlib
pushgateway_basic_auth_username: pushgateway
pushgateway_basic_auth_password: "{{ vault_pushgateway_basic_auth_password}}"
pushgateway_hostname: pushgateway01
pushgateway_args:
  - --web.listen-address={{ pushgateway_port }}
  - --web.route-prefix="/pushgateway"
  - --persistence.file=/pushgateway/state
