- name: "Create {{ role_name }} volume"
  docker_volume:
    name: "{{ odoo_volume_name }}"

- name: Git ssh checkout
  git:
    repo: "{{ odoo_enterprise_repo }}"
    dest: "{{ odoo_data_dir }}/enterprise"
    key_file: "{{ odoo_enterprise_key_file }}"
    version: "{{ odoo_enterprise_commit }}"
    accept_hostkey: true
    force: true
  ignore_errors: true
  changed_when: false
  when: odoo_enterprise_repo is regex('git@')

- name: Git https checkout
  git:
    repo: "https://{{odoo_enterprise_access_username|urlencode()}}:{{odoo_enterprise_access_token|urlencode()}}@github.com/odoo/enterprise.git"
    dest: "{{ odoo_data_dir }}/enterprise"
    version: "{{ odoo_enterprise_commit }}"
    accept_hostkey: true
    force: true
  ignore_errors: true
  changed_when: false
  when: odoo_enterprise_repo is regex('https:\/\/')

- name: Ensure auto install is disabled
  script: "disable-auto-install {{ odoo_data_dir }}"
  changed_when: false