---
- name: Include {{ role_name }} tasks
  ansible.builtin.include_tasks: "{{ role_name }}.yml"
  tags:
    - odoo

- name: On build set new image tag {{ role_name }}:{{ odoo_hostname }}
  ansible.builtin.set_fact:
    odoo_image: "odoo:{{ odoo_hostname }}"
    odoo_build_image: "{{ odoo_image }}"
  when: odoo_build_image and odoo_image.startswith('odoo')
  tags:
    - odoo

- name: On build set new image tag mintsystem:{{ odoo_hostname }}
  ansible.builtin.set_fact:
    odoo_image: "mintsytem:{{ odoo_hostname }}"
    odoo_build_image: "{{ odoo_image }}"
  when: odoo_build_image and odoo_image.startswith('mintsystem')
  tags:
    - odoo

- name: Include {{ role_name }} build tasks
  ansible.builtin.include_tasks: "{{ role_name }}_build.yml"
  when: odoo_build_image and odoo_build_image != odoo_image
  tags:
    - odoo

- name: Include {{ role_name }} tasks
  ansible.builtin.include_tasks: "{{ role_name }}.yml"
  when: odoo_image is defined
  tags:
    - odoo

- name: Include {{ role_name }} backup from restic client role
  ansible.builtin.include_role:
    name: restic
    apply:
      tags:
        - odoo_backup
    tasks_from: restic_odoo_backup
  vars:
    restic_backup_set: "{{ odoo_backup_set }}"
  when: odoo_backup_set is defined
  tags:
    - restic
    - odoo_backup
