---
- name: Ensure {{ role_name }} k8s dir exists
  ansible.builtin.file:
    path: "/srv/k8s/{{ role_name }}"
    state: directory

- name: Template {{ role_name }} k8s manifest files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/srv/k8s/{{ role_name }}/{{ item }}"
  loop:
    - k8s_iam.yaml

- name: Apply {{ role_name }} k8s manifest files
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    namespace: "{{ k8s_namespace }}"
    state: present
    src: "/srv/k8s/{{ role_name }}/{{ item }}"
  loop:
    - k8s_iam.yaml