---
- name: Remove postgres container {{ postgres_hostname }}
  community.docker.docker_container:
    name: "{{ postgres_hostname }}"
    state: absent

- name: Remove pgadmin data dir
  ansible.builtin.file:
    path: "{{ postgres_data_dir }}"
    state: absent
  when: '"postgres_data" in ansible_run_tags'

- name: Remove postgres volume {{ postgres_volume_name }}
  community.docker.docker_volume:
    name: "{{ postgres_volume_name }}"
    state: absent
  when: '"postgres_volume" in ansible_run_tags'
