---
- name: Ensure {{ role_name }} scripts dir exists
  ansible.builtin.file:
    path: "{{ cron_scripts_dir }}"
    state: directory

- name: Copy {{ role_name }} scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ cron_scripts_dir }}/{{ item }}"
    mode: +x
  loop:
    - cron-job-run
    - cron-job-list
    - write-node-exporter-metric
