---
acme_sh_data_dir: /usr/share/{{ acme_sh_hostname }}
acme_sh_description: Acme.sh
acme_sh_freedns_password: "{{ vault_dns_freedns_password }}"
acme_sh_vercel_token: "{{ vault_dns_vercel_token }}"
acme_sh_infomaniak_api_token: "{{ vault_dns_infomaniak_token }}"
