---
metabase_build_image: false
metabase_configmap: [hostname: metabase01-prod]
metabase_description: Metabase
metabase_state: started
metabase_timezone: Europe/Zurich
metabase_db_type: postgres
metabase_db_port: "5432"
metabase_db_dbname: metabase
metabase_db_user: metabase
metabase_db_pass: "{{ vault_metabase_db_pass }}"
