---
- name: Register selective docker mysql backup jobs
  ansible.builtin.cron:
    name: "{{ item.id }}"
    hour: "{{ item.hour }}"
    minute: "{{ 59 | random(seed=item.id) }}"
    job: docker-mysql-backup -c {{ item.container }} -d {{ item.databases }} -o {{ restic_backup_dir }} {{ '&& restic-main backup ' + restic_backup_dir + '/' +
      item.container + ' --tag ' + (item.tags | join(' --tag ')) if item.upload | default(true) else '' }}; write-node-exporter-metric -c '{{ item.id }}' -v $?
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ restic_backup_set }}"
  when: item.type == "mysql-dump" and item.databases is defined

- name: Register docker mysql backup jobs
  ansible.builtin.cron:
    name: "{{ item.id }}"
    hour: "{{ item.hour }}"
    minute: "{{ 59 | random(seed=item.id) }}"
    job: docker-mysql-backup -c {{ item.container }} -o {{ restic_backup_dir }} -a {{ '&& restic-main backup ' + restic_backup_dir + '/' + item.container + '
      --tag ' + (item.tags | join(' --tag ')) if item.upload | default(true) else '' }}; write-node-exporter-metric -c '{{ item.id }}' -v $?
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ restic_backup_set }}"
  when: item.type == "mysql-dump" and item.databases is undefined
