docker_network_name: mint-system.com
ansible_become: true
ufw_enabled: false
etc_hosts:
  - ip: 127.0.0.1
    name: n8n.local odoo.local metabase.local grafana.local chatgpt.local login.local

iam_groups:
  - name: wheel
    sudoers_commands: ALL
  - name: operators
    sudoers_commands: /usr/bin/docker ps, /usr/bin/docker start *,  /usr/bin/docker stop *, /usr/bin/docker restart *
iam_users:
  - username: admin
    state: present
    groups: wheel,docker
    hosts: "{{ groups.all }}"
  - username: operator
    state: present
    groups: operators
    hosts: "{{ groups.all }}"

# https://hub.docker.com/_/postgres
postgres_image: postgres:17-alpine
# postgres_build_image: true # default: false
postgres_hostname: postgres01
postgres_user: example
postgres_configmap:
  - db: metabase-prod
  - db: n8n-prod
  - db: odoo-prod
  - db: odoo-int
  - db: keycloak
postgres_password: test
postgres_wal_level: logical

# https://hub.docker.com/r/getmeili/meilisearch
meilisearch_image: getmeili/meilisearch:v1.10.1
meilisearch_hostname: meili01
meilisearch_volume_name: "{{ meilisearch_hostname }}"
meilisearch_master_key: "test"
meilisearch_network_mode: host
meilisearch_task_webhook: http://host.docker.internal:8069/meilisearch/task-webhook
meilisearch_etc_hosts:
  "host.docker.internal": host-gateway

meilisearch_url: http://localhost:7700
meilisearch_base_path: "{{ inventory_dir}}/host_vars/"
meilisearch_api_keys:
  - path: api_keys/odoo.json
meilisearch_indexes:
  - path: indexes/res_country_state.json

# https://hub.docker.com/r/dpage/pgadmin4/
pgadmin_image: dpage/pgadmin4:7.6
pgadmin_hostname: pgadmin01
pgadmin_user: admin@example.com
pgadmin_password: example
pgadmin_servers:
  - name: Postgres
    host: postgres01
    username: example
pgadmin_data_dir: /usr/share/{{ pgadmin_hostname }}
pgadmin_volume_name: "{{ pgadmin_hostname }}"

# https://hub.docker.com/r/n8nio/n8n/tags
n8n_image: n8nio/n8n:1.67.1
n8n_hostname: n8n01
n8n_postgresdb_host: postgres01
n8n_postgresdb_user: example
n8n_postgresdb_password: test
n8n_secure_cookie: "false"
n8n_configmap:
  - hostname: n8n01-prod
    database: n8n-prod
    webhook_url: ""

# https://quay.io/repository/keycloak/keycloak
keycloak_image: quay.io/keycloak/keycloak:24.0
keycloak_hostname: keycloak01
keycloak_admin: admin
keycloak_admin_password: admin
keycloak_db_url_host: postgres01
keycloak_db_username: example
keycloak_db_password: test
keycloak_proxy_hostname: http://login.local

# https://hub.docker.com/_/nginx/
nginx_image: nginx:1.26.2-alpine
nginx_hostname: nginx01
nginx_http_options: |
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }
nginx_ports:
  - 8080:80
nginx_proxies:
  - src_hostname: metabase.local
    dest_hostname: metabase01-prod
    dest_port: 3000
  - src_hostname: n8n.local
    dest_hostname: n8n01-prod
    dest_port: 5678
  - src_hostname: odoo.local
    dest_hostname: odoo01-prod
    dest_port: 8069
    locations:
      - path: /websocket
        dest_hostname: odoo01-prod
        dest_port: 8072
        options: |
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          include /etc/nginx/conf.d/proxy-params.conf;
      - path: /website/info
        options:
          |
          deny all;
  - src_hostname: grafana.local
    dest_hostname: grafana01
    dest_port: 3000
  - src_hostname: login.local
    dest_hostname: keycloak01
    dest_port: 8080
  - src_hostname: chatgpt.local
    dest_hostname: open_webui01
    dest_port: 8080

# https://hub.docker.com/r/mintsystem/odoo/
odoo_revision: "18.0"
odoo_image: mintsystem/odoo:18.0
odoo_hostname: odoo01
odoo_description: Odoo 18
odoo_master_password: odoo
odoo_postgres_user: example
odoo_postgres_password: test
odoo_configmap:
  - hostname: odoo01-prod
  - hostname: odoo01-int
odoo_addons_git_repos: https://github.com/OCA/partner-contact.git#18.0
odoo_postgres_hostname: "{{ postgres_hostname }}"

# https://hub.docker.com/r/metabase/metabase
metabase_image: metabase/metabase:v0.51.12.1
metabase_hostname: metabase01
metabase_db_host: postgres01
metabase_db_user: example
metabase_db_pass: test

# https://hub.docker.com/r/prom/node-exporter
node_exporter_image: prom/node-exporter:v1.0.1
node_exporter_hostname: node01
node_exporter_nginx_enabled: false

# https://hub.docker.com/r/prom/prometheus
prometheus_image: prom/prometheus:v2.54.1
prometheus_hostname: prom01

# https://hub.docker.com/r/grafana/loki/
loki_image: grafana/loki:3.3.2
loki_hostname: loki01

# https://hub.docker.com/r/grafana/promtail/
promtail_image: grafana/promtail:3.3.2
promtail_hostname: promtail01
promtail_push_url: http://loki01:3100/loki/api/v1/push

# https://hub.docker.com/r/grafana/grafana/
grafana_image: grafana/grafana:11.2.0
grafana_hostname: grafana01
grafana_admin_user: admin
grafana_admin_password: admin
grafana_prometheus_hostname: prom01
grafana_server_domain: "grafana.local"
grafana_server_root_url: "http://grafana.local"

# https://github.com/open-webui/open-webui
open_webui_image: ghcr.io/open-webui/open-webui:v0.7.2
open_webui_hostname: open_webui01
open_webui_volume_name: "{{ open_webui_hostname }}"
open_webui_ports:
  - "8081:8080"
open_webui_oauth_client_id: chatgpt.localhost
open_webui_oauth_client_secret: ""
open_webui_openid_provider_url: ""

docker_compose_project_name: project01
docker_compose_dotenv: |
  POSTGRES_PASSWORD=postgres
docker_compose_definition:
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    web:
      image: django
      command: python -m http.server
      ports:
        - "8000:8000"
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      depends_on:
        - db