- name: Create nextcloud volume
  docker_volume:
    name: "{{ nextcloud_volume_name }}"
  when: nextcloud_volume_name is defined

- name: Ensure nextcloud data dir exists
  file:
    path: "{{ nextcloud_data_dir }}"
    state: directory
  when: nextcloud_data_dir is defined

- name: Start nextcloud container
  docker_container:
    name: "{{ nextcloud_hostname }}"
    image: "{{ nextcloud_image }}"
    restart_policy: unless-stopped
    env:
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSSWORD: "{{ nextcloud_admin_password }}"
      POSTGRES_HOST: "{{ nextcloud_postgres_hostname }}"
      POSTGRES_USER: "{{ nextcloud_postgres_user }}"
      POSTGRES_PASSWORD: "{{ nextcloud_postgres_password }}"
      POSTGRES_DB: "{{ nextcloud_postgres_db }}"
    volumes:
      - "{{ nextcloud_volume_name }}:/var/www/html"
    networks:
      - name: "{{ docker_network_name }}"
    log_driver: "{{ docker_log_driver }}"
    log_options:
      max-size: "{{ docker_log_max_size }}"
      max-file: "{{ docker_log_max_file }}"
