---
open_webui_image: ghcr.io/open-webui/open-webui:v0.7.0
open_webui_description: Open WebUI
open_webui_hostname: open-webui
open_webui_volume_name: "{{ open_webui_hostname }}"
open_webui_volumes:
  - "{{ open_webui_volume_name }}:/app/backend/data"
open_webui_ports:
  - "8080:8080"
open_webui_oauth_client_secret: "{{ vault_open_webui_oauth_client_secret }}"
open_webui_proivder_name: SSO
