---
loki_requires_package: python3-passlib
loki_description: Loki
loki_data_dir: /usr/share/{{ loki_hostname }}
loki_nginx_data_dir: "{{ nginx_data_dir }}/proxies"
loki_basic_auth_username: loki
loki_basic_auth_password: "{{ vault_loki_basic_auth_password }}"
loki_retention_period: 14d
