---
- name: Ensure nginx data dir exists
  ansible.builtin.file:
    path: "{{ n8n_exporter_nginx_data_dir }}"
    state: directory

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Fail if package {{ n8n_exporter_requires_package }} is not installed
  ansible.builtin.fail:
    msg: Package {{ n8n_exporter_requires_package }} is not installed!
  when: n8n_exporter_requires_package not in ansible_facts.packages

- name: Configure user access for {{ role_name }}
  community.general.htpasswd:
    path: "{{ n8n_exporter_nginx_data_dir }}/n8n-exporter.htpasswd"
    name: "{{ n8n_exporter_basic_auth_username }}"
    password: "{{ n8n_exporter_basic_auth_password }}"

- name: Copy {{ role_name }} nginx config
  ansible.builtin.template:
    src: n8n-exporter.nginx
    dest: "{{ n8n_exporter_nginx_data_dir }}/n8n-exporter.nginx"
