---
moodle_volume_name: "{{ moodle_hostname }}"
odoo_data_dir: /usr/share/{{ odoo_hostname }}
odoo_configmap:
  - hostname: odoo01-prod
odoo_volume_name: "{{ odoo_hostname }}"
postgres_volume_name: "{{ postgres_hostname }}"
nginx_data_dir: "/usr/share/{{ nginx_hostname }}"
metabase_configmap: [hostname: metabase01-prod]
loki_data_dir: /usr/share/{{ loki_hostname }}
promtail_data_dir: /usr/share/{{ promtail_hostname }}
grafana_data_dir: /usr/share/{{ grafana_hostname }}
grafana_volume_name: "{{ grafana_hostname }}"
prometheus_volume_name: "{{ prometheus_hostname }}"
prometheus_data_dir: /usr/share/{{ prometheus_hostname }}
docker_compose_data_dir: /srv/compose/{{ docker_compose_project_name }}
fail2ban_packages:
  - name: fail2ban
docker_build_dir: /srv/build
