- name: Verify file path exists
  command: "ls {{ item.path }}"
  changed_when: false
  loop: "{{ restic_backup_set }}"
  when: item.type == "file"

- name: Register file backup jobs
  cron:
    name: "Backup job {{ item.id }}"
    hour: "{{ item.hour }}"
    minute: "{{ 59 |random(seed=item.id) }}"
    job: "restic backup {{ item.path }} --tag {{ item.tags | join(' --tag ') }} \
      {{ '--help' if item.upload | default(false) else '' }}; \
      write-node-exporter-metric -c 'Backup job {{ item.id }}' -v $?"
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ restic_backup_set }}"
  when: item.type == "file"