- name: Verify odoo backup command exists
  shell: "ls $(which odoo-backup)"
  changed_when: false
  loop: "{{ restic_backup_set }}"
  when: item.type == "odoo-backup"

- name: Register odoo backup jobs
  cron:
    name: "Backup job {{ item.id }}"
    hour: "{{ item.hour }}"
    minute: "{{ 59 |random(seed=item.id) }}"
    job: "odoo-backup -d {{ item.database }} -h {{ item.host | default('http://localhost:8069') }} \
      && restic backup /var/tmp/{{ item.database }}.zip --tag {{ item.tags | join(' --tag ') }} \
      {{ '--help' if item.upload | default(false) else '' }}; \
      write-node-exporter-metric -c 'Backup job {{ item.id }}' -v $?"
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ restic_backup_set }}"
  when: item.type == "odoo-backup"

- name: Register odoo backup jobs
  cron:
    name: "Backup job {{ item.id }}"
    hour: "{{ item.hour }}"
    minute: "{{ 59 |random(seed=item.id) }}"
    job: "docker-odoo-backup -d {{ item.database }} -c {{ item.container }} \
      && restic backup /var/tmp/{{ item.database }}.zip --tag {{ item.tags | join(' --tag ') }} \
      {{ '--help' if item.upload | default(false) else '' }}; \
      write-node-exporter-metric -c 'Backup job {{ item.id }}' -v $?"
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ restic_backup_set }}"
  when: item.type == "docker-odoo-backup"