- name: Register selective docker mysql backup jobs
  cron:
    name: "Backup job {{ item.id }}"
    hour: "{{ item.hour }}"
    minute: "{{ 59 |random(seed=item.id) }}"
    job: "docker-mysql-backup -c {{ item.container }} -d {{ item.databases }} \
      && restic backup /var/tmp/{{ item.container }} --tag {{ item.tags | join(' --tag ') }} \
      {{ '--help' if item.upload | default(false) else '' }}; \
      write-node-exporter-metric -c 'Backup job {{ item.id }}' -v $?"
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ restic_backup_set }}"
  when: item.type == "mysql-dump" and item.databases is defined

- name: Register docker mysql backup jobs
  cron:
    name: "Backup job {{ item.id }}"
    hour: "{{ item.hour }}"
    minute: "{{ 59 |random(seed=item.id) }}"
    job: "docker-mysql-backup -c {{ item.container }} -a \
      && restic backup /var/tmp/{{ item.container }} --tag {{ item.tags | join(' --tag ') }} \
      {{ '--help' if item.upload | default(false) else '' }}; \
      write-node-exporter-metric -c 'Backup job {{ item.id }}' -v $?"
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ restic_backup_set }}"
  when: item.type == "mysql-dump" and item.databases is undefined