---
- name: Ensure nginx data dir exists
  ansible.builtin.file:
    path: "{{ nginx_data_dir }}/proxies"
    state: directory

- name: Configure user access for {{ role_name }}
  community.general.htpasswd:
    path: "{{ nginx_data_dir }}/proxies/prometheus.htpasswd"
    name: "{{ prometheus_basic_auth_username }}"
    password: "{{ prometheus_basic_auth_password }}"

- name: Copy {{ role_name }} nginx config
  ansible.builtin.template:
    src: prometheus.nginx
    dest: "{{ nginx_data_dir }}/proxies/prometheus.nginx"

- name: Copy {{ role_name }} write endpoint nginx config
  ansible.builtin.template:
    src: prometheus-write-endpoint.nginx
    dest: "{{ nginx_data_dir }}/proxies/prometheus-write-endpoint.nginx"
  when: prometheus_write_endpoint_enabled
