---
- name: Ensure {{ role_name }} scripts dir exists
  ansible.builtin.file:
    path: "{{ docker_scripts_dir }}"
    state: directory

- name: Copy backup scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ docker_scripts_dir }}/{{ item }}"
    mode: +x
  loop:
    - docker-export
    - docker-import
