---
postgres_build_image: false
postgres_description: PostgreSQL
postgres_volume_name: "{{ postgres_hostname }}"
postgres_db: "{{ postgres_user }}"
postgres_password: "{{ vault_postgres_password }}"
postgres_data_dir: /usr/share/{{ postgres_hostname }}
postgres_volumes:
  - "{{ postgres_volume_name }}:/var/lib/postgresql/data"
postgres_ports: []
postgres_wal_level: replica
postgres_max_connections: 100
